{
  "hash": "d132d53a7b06d320d632d1f7596f9ba5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introducing Cox regression\"\neditor: visual\n---\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nIn this chapter, we'll explore simple Cox regression models and how to interpret their output.\n\nNote that this chapter only features code in R. It will be updated in future to include Python.\n\n## Libraries and functions\n\n:::: {.callout-note collapse=\"true\"}\n## Click to expand\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the required packages for fitting & visualising\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(survminer)\n```\n:::\n\n\n\n\n## Python\n\n\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom lifelines import *\nimport matplotlib.pyplot as plt\nfrom lifelines.statistics import multivariate_logrank_test\nfrom lifelines.statistics import pairwise_logrank_test\n```\n:::\n\n\n\n:::\n::::\n\n## When do you need Cox regression?\n\nSo far our focus has been on the log-rank test, which is useful to make comparisons between two or three survival curves.\n\nHowever, it has its limits.\n\nCox regression is more flexible and can be used to build more complex models than a log-rank test can manage.\n\nYou would need to use Cox regression (rather than a log-rank test) when:\n\n- You want to make predictions about survival based on values of the predictor/independent variable(s)\n- You have more than one predictor variable\n- Your predictor variable(s) are continuous, rather than categorical\n\n## The basic idea\n\nIn a linear model, we predict values of a continuous outcome variable `y`. But in a Cox regression, we predict values of something called the **hazard function**.\n\nBroadly speaking, you can interpret this hazard function as the risk of the event of interest occurring at a given time, under certain values of the predictor variable(s).\n\nConceptually, it's a bit like a generalised linear model: a linear model that has been extended or transformed, to allow us to predict something that isn't a continuous outcome variable.\n\n### A little more information\n\nFor more of the mathematical theory, you can check out the drop-down boxes below.\n\nThis level of understanding is **not necessary** for being able to apply Cox regression. If you prefer just to think about data and implementation, you can skip this and move on to the next section.\n\nIt might be helpful, however, to return to some of these ideas when the concept of proportional hazards comes up later in the course.\n\n::: {.callout-note collapse=\"true\"}\n#### The survival function\n\nThere is a random variable $T$ that represents a subject's true time-to-event (often referred to as \"survival time\"). We can't always observe $T$ directly because of censoring.\n\nWe also have $t$, which just represents time passing in its normal fashion (we won't get into any relativity here, don't worry...)\n\nThe survival function, which we can draw as a curve, shows the probability of an individual's true time-to-event $T$ exceeding a given time $t$, which we can write as $S(t) = P(T > t)$. In other words, it measures how likely an individual is to \"survive\" beyond a particular time without experiencing the event of interest.\n\nSince the output of this function is a probability, it will always take values between 0 and 1. Generally the probability will decrease as $t$ increases, but usually not linearly.\n\n(Officially, this survival function asymptotes to 0, or in other words it approaches 0 as $t \\rightarrow \\infty$ , implying that after an infinite amount of time every individual will experience the event.)\n\nA standard survival function might look something like this:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-cox-regression_files/figure-html/standard survival function-1.png){width=672}\n:::\n:::\n\n\n\n\nThe Kaplan-Meier estimator that we looked at in previous chapters is designed to estimate the survival function $S(t)$. Of course we usually don't have enough data to make it look this smooth and our data is usually censored, which is why we get a \"staircase\"-style approximation.\n\nIn Cox regression, however, we don't estimate the survival function directly. Instead, we measure a related function, the hazard function.\n:::\n\n::: {.callout-note collapse=\"true\"}\n#### The hazard function\n\nThe hazard function, $h(t)$, captures for any given time $t$ the instantaneous rate at which events will occur (it's sometimes also called the hazard rate for this reason).\n\nFor example, at a single point exactly 10 days into a clinical study, how many people would you be expecting to go into remission? Or at a single point exactly 5 years into their lifespan, how many machines in a factory would you be expecting to fail?\n\nIn the plot below there are a few examples of different hazard functions:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-cox-regression_files/figure-html/examples of hazard functions-1.png){width=672}\n:::\n:::\n\n\n\n\n#### Cumulative hazard\n\nWe can also track something called the cumulative hazard function, which we denote as $H(t)$ - notice the capital H this time.\n\nThis tracks the total amount of hazard that an individual has accumulated up to time $t$.\n\nIt is impossible for the cumulative hazard function to ever decrease, because the hazard function is not negative - i.e., the total amount of hazard can only decrease or remain the same.\n\n(From a mathematical perspective, the hazard function $h(t)$ is the first derivative of the cumulative hazard function $H(t)$, i.e., $h(t)$ captures the gradient of $H(t)$.)\n\nHere are the cumulative hazard functions associated with the hazard functions above:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-cox-regression_files/figure-html/cumulative hazards associated with above functions-1.png){width=672}\n:::\n:::\n\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n#### The link between the hazard and survival functions\n\nThe survival function, hazard function and cumulative hazard function all link to each other and can be calculated from each other.\n\nLet's revisit the cumulative hazard functions shown in the plot above, and look at the corresponding survival functions:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](05-cox-regression_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\nNotice how the quicker we build up cumulative hazard on the left, the faster the survival function drops towards 0 on the right.\n\nIn Cox regression (unlike in Kaplan-Meier estimation), we estimate the hazard function. But by doing this, we can then infer the survival function as well.\n:::\n\n::: {.callout-note collapse=\"true\"}\n#### Transforming a linear model to predict hazard\n\nThe equation for a Cox regression looks like this:\n\n$$h(t) = h_0(t) \\times exp(\\beta_1x_1 + \\beta_2x_2 + ... + \\beta_nx_n)$$\n\n$h(t)$ is the hazard function. This is what we are predicting values of, i.e, it is our outcome of interest. It is a function of time, meaning that we are predicting the hazard $h$ at time $t$. If we plotted it on a graph, $h$ would go on the y-axis and $t$ on the x-axis.\n\n$h_0(t)$ is the baseline hazard, and it acts as the intercept in our model (notice there's no $\\beta_0$). This means it is the value of the hazard function when all our predictor variables $x_1, x_2, ... x_n = 0$ .\n\nThis baseline hazard still varies over time!\n\nThe part you will likely recognise is inside the brackets, and it's called the linear predictor: $\\beta_1x_1 + \\beta_2x_2 + ... + \\beta_nx_n$. This is essentially a linear equation that is getting embedded inside another function/equation.\n\nIn this case, the non-linear part of the equation is quite simple: we're raising Euler's number $e$ to the power of our linear predictor (known as exponentiating).\n:::\n\n## Fitting a simple Cox model\n\nWe'll return to our `hospital_stays.csv` dataset.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhospital_stays <- read_csv(\"data/hospital_stays.csv\")\n```\n:::\n\n\n\n:::\n\nIn this chapter, we'll keep things simple by fitting a Cox regression with just one continuous predictor `age`.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_hosp <- coxph(Surv(time, discharged) ~ age,\n                  data = hospital_stays)\n\nsummary(cox_hosp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, discharged) ~ age, data = hospital_stays)\n\n  n= 210, number of events= 189 \n\n         coef exp(coef)  se(coef)      z Pr(>|z|)    \nage -0.053128  0.948259  0.006116 -8.686   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n    exp(coef) exp(-coef) lower .95 upper .95\nage    0.9483      1.055     0.937    0.9597\n\nConcordance= 0.68  (se = 0.021 )\nLikelihood ratio test= 73.28  on 1 df,   p=<2e-16\nWald test            = 75.45  on 1 df,   p=<2e-16\nScore (logrank) test = 78.37  on 1 df,   p=<2e-16\n```\n\n\n:::\n:::\n\n\n\n\nThe syntax is identical to the `survfit` function we used in previous chapters: we provide a formula with the structure `survival object ~ predictor(s)`, and then the dataset.\n:::\n\nThere! You've just fitted a Cox regression model to a time-to-event dataset.\n\nWe can see that we're given some basic information to start with. This includes the total number of individuals, and the total number of events. The difference between these two numbers tells us how many individuals were censored in our study (in this case, $210-189 = 21$ were censored).\n\nUnderneath that is where we start to get into the interpretation.\n\n## The hazard ratio\n\nWe've been provided with a row of quantities corresponding to our single predictor variable `age`. The most important one to focus on is the hazard ratio, which is the `exp(coef)` value.\n\nIt's not essential to understand how it's calculated, but if you're curious, you can open the drop-down below for more information.\n\n\\[INSERT DROP DOWN\\]\n\nThe most important thing to know is how to interpret this hazard ratio.\n\nIn the context of a continuous predictor variable, as we have here, the hazard ratio measures the change in the instantaneous risk of an event occurring for each one-unit increase in that variable, assuming everything else stays constant.\n\nIn other words, for each additional year of `age`, how much does the \"risk\" of being discharged from hospital change? When:\n\n- HR = 1, this implies that the predictor has no effect on the risk\n- HR \\> 1, risk is increased as the predictor increases\n- HR \\< 1, risk is decreased as the predictor increases\n\nIn our example here, our hazard ratio is 0.9483. This tells us that each one-year increase in age is associated with a \"risk\" of hospital discharge that is 0.9483 times as large (about 5.2% lower) than that of someone one year younger. (So, being younger gets you discharged a tiny bit quicker.)\n\n::: {.callout-warning appearance=\"minimal\" icon=\"false\"}\n#### How did I calculate that % change?\n\nLike so:\n\n$(0.9483 - 1) \\times 100 = -5.17$\n\nThe general formula is:\n\n$(HR - 1) \\times 100$\n\nIf the answer is positive, that means an increase in hazard; if it's negative, that's a decrease.\n:::\n\nA 5.2% change might not seem like very much, but when we're dealing with continuous predictors, hazard ratios that don't seem far away from 1 can occur quite often. Remember that we're only looking a single unit increase in the predictor (so just one year, in this example).\n\nThe effect will compound over multiple years; if we wanted to look at a 10-year age difference, for example, we can do that by raising our hazard ratio to a power of 10:\n\n$0.9483^{10} \\approx 0.59$\n\nmeaning that a patient who is 10 years younger has an approximately 59% higher chance of being discharged than an otherwise similar, but older, patient.\n\nThat feels more like a \"result\", don't you think?\n\n### How confident are we?\n\nWe also want to pay attention to the confidence intervals around our hazard ratio. The wider the interval, the less confident we should feel about the estimate of our confidence interval, and the less stock we should put in its value.\n\nIn our case, our interval is quite narrow:\n\n$0.9597 - 0.937 = 0.0227$\n\nand crucially, our confidence interval doesn't \"cross over\" with 1 (remember that when the ratio = 1, this implies no effect of the predictor).\n\nSo overall, we can probably be pretty happy with our hazard ratio estimate.\n\n## Global significance tests\n\nUnderneath the information about the `age` predictor, we get some information about the model as a whole. The first number, concordance, will be discussed in the next chapter; here, we'll focus on the global significance tests.\n\nThese tests are looking at the model as a whole. When we have multiple predictor variables, these global significance tests will give quite different results to significance tests of individual predictors.\n\nThere are three different methods for doing this:\n\n- a Wald test\n- a likelihood ratio test\n- a log-rank/score test\n\nThe Wald test doesn't work great when the sample size is small, and/or the coefficients are large. The score (log-rank) test is often better than the Wald test, but it doesn't use as much information as the likelihood ratio test does.\n\nThis means that **the best option of the three is the likelihood ratio test**.\n\nIn the LRT, we are comparing our model against a null model, i.e., a model that contains no predictors at all. So we are asking whether our set of predictors, overall, does a better job of explaining our data than having no predictors at all.\n\n## Exercises\n\n### Lung cancer {#sec-exr_lung}\n\n:::: callout-exercise\n\n\n\n{{< level 2 >}}\n\n\n\n\n\n\nFor this example, we'll use the `lung` dataset inbuilt into the `survival` package.\n\nIf you're having trouble loading it up, you can use the following code:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlung <- force(lung)\n```\n:::\n\n\n\n:::\n\nThis is a dataset about patients with advanced lung cancer, from the North Central Cancer Treatment Group. The event of interest is death.\n\nThis is a complex dataset with a lot of predictors. Key ones include:\n\n- `time`: survival time in days\n- `status`: whether the subject was censored; 1=censored, 2=dead (event occurred)\n- `age`: given in years\n- `wt.loss`: weight loss over the last six months (in pounds, lbs)\n\nFor this exercise, you should try to answer the following questions using Cox regression and the hazard ratios:\n\n1.  How much is the hazard increased by a 5-year age increase?\n2.  How much is the hazard increased by a 5lb weight loss?\n3.  Do the hazard ratios change for each predictor if you include them in a model simultaneously (versus a separate model for each)?\n\nNote: before you get started, you will need to recode the `status` censoring variable, as it's been coded in a non-standard way in this dataset:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlung <- lung %>%\n  mutate(status = recode(status, `1`=0, `2`=1))\n```\n:::\n\n\n\n:::\n\n::: callout-answer\n##### Age predictor\n\nLet's start by focusing on the `age` research question first.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_lung_age <- coxph(Surv(time, status) ~ age, \n                  data = lung)\n\nsummary(cox_lung_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ age, data = lung)\n\n  n= 228, number of events= 165 \n\n        coef exp(coef) se(coef)     z Pr(>|z|)  \nage 0.018720  1.018897 0.009199 2.035   0.0419 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n    exp(coef) exp(-coef) lower .95 upper .95\nage     1.019     0.9815     1.001     1.037\n\nConcordance= 0.55  (se = 0.025 )\nLikelihood ratio test= 4.24  on 1 df,   p=0.04\nWald test            = 4.14  on 1 df,   p=0.04\nScore (logrank) test = 4.15  on 1 df,   p=0.04\n```\n\n\n:::\n:::\n\n\n\n:::\n\nThe hazard ratio is the `exp(coef)`, 1.019. For each additional year of age, there is a modest increase in hazard (i.e., chance of death).\n\nSpecifically, each additional year of age is associated with approximately a 1.9% increase in the instantaneous risk of death.\n\nIf I want to know how this compounds over 5 years, I raise my hazard ratio to the power 5:\n\n$1.018897^5 = 1.098124$\n\nwhich corresponds to a 9.8% increase in hazard.\n\n##### Weight loss predictor\n\nNow let's look at the `wt.loss` predictor.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_lung_wt <- coxph(Surv(time, status) ~ wt.loss, \n                  data = lung)\n\nsummary(cox_lung_wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ wt.loss, data = lung)\n\n  n= 214, number of events= 152 \n   (14 observations deleted due to missingness)\n\n            coef exp(coef) se(coef)     z Pr(>|z|)\nwt.loss 0.001319  1.001320 0.006079 0.217    0.828\n\n        exp(coef) exp(-coef) lower .95 upper .95\nwt.loss     1.001     0.9987    0.9895     1.013\n\nConcordance= 0.525  (se = 0.027 )\nLikelihood ratio test= 0.05  on 1 df,   p=0.8\nWald test            = 0.05  on 1 df,   p=0.8\nScore (logrank) test = 0.05  on 1 df,   p=0.8\n```\n\n\n:::\n:::\n\n\n\n:::\n\nThis is a more modest effect. With a hazard ratio of 1.001320, we're looking at around a 0.1% increase in hazard with each pound lost.\n\nEven if we look at how this stacks for a 5lb weight loss:\n\n$1.001320^5 = 1.006617$\n\nthis is only a \\~0.7% increase.\n\n##### Both predictors\n\nFinally, let's look at what happens when we include both predictors in the model simultaneously (without an interaction, to keep things simple).\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_lung <- coxph(Surv(time, status) ~ age + wt.loss, \n                     data = lung)\n\nsummary(cox_lung)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, status) ~ age + wt.loss, data = lung)\n\n  n= 214, number of events= 152 \n   (14 observations deleted due to missingness)\n\n            coef exp(coef) se(coef)     z Pr(>|z|)  \nage     0.021697  1.021934 0.009627 2.254   0.0242 *\nwt.loss 0.001339  1.001340 0.006239 0.215   0.8301  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n        exp(coef) exp(-coef) lower .95 upper .95\nage         1.022     0.9785    1.0028     1.041\nwt.loss     1.001     0.9987    0.9892     1.014\n\nConcordance= 0.563  (se = 0.026 )\nLikelihood ratio test= 5.27  on 2 df,   p=0.07\nWald test            = 5.12  on 2 df,   p=0.08\nScore (logrank) test = 5.14  on 2 df,   p=0.08\n```\n\n\n:::\n:::\n\n\n\n::::\n\nOur hazard ratios haven't changed *very* much, but they are not identical.\n\nSo: yes! Including both predictors together does change things (a bit).\n\nIn later chapters, we'll look at models with multiple predictors. But if you're the type who likes thinking ahead, you can use what you already know about linear modelling to start thinking about *why* this change might've occurred, and whether our two-predictor model might be better.\n:::\n::::\n\n## Summary\n\nA Cox model is more complex than a log-rank test, but also more flexible, and can be used for a wider variety of datasets. Here, we've shown how it can be applied to a dataset with a single continuous predictor, but we'll add complexity in subsequent chapters.\n\nWhen interpreting a Cox model, we can look at individual predictors or the model as a whole. The best metric to interpret is the hazard ratio.\n\n::: callout-tip\n#### Key Points\n\n- Cox regression can be used to model survival (time-to-event) data when we have a continuous predictor\n- In Cox regression, we are most interested in interpreting the hazard ratio, which tells us about the increase in hazard/risk as our predictor changes\n- We can also extract p-values in multiple ways from a Cox model, with slightly different interpretations\n:::\n",
    "supporting": [
      "05-cox-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}