{
  "hash": "bba23518e563f271b8de3cf34e0cfe94",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Interpreting more complex models\"\neditor: visual\n---\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'pec' was built under R version 4.5.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'prodlim' was built under R version 4.5.3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nLast chapter, we learned how to fit Cox regression models with more than one predictor, and how to check their assumptions.\n\nOnce we're sure that a model is valid, how can we interpret it?\n\n::: callout-warning\n**This chapter is still in development.**\n\nNote that this chapter only features code in R. We hope to update it in future to include Python.\n:::\n\n## Libraries and functions\n\n:::: {.callout-note collapse=\"true\"}\n## Click to expand\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the required packages for fitting & visualising\nlibrary(tidyverse)\nlibrary(survival)\nlibrary(survminer)\n\n# In this chapter, we will use a new package\ninstall.packages(\"pec\")\nlibrary(pec)\n```\n:::\n\n\n## Python\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport pandas as pd\nfrom lifelines import *\nimport matplotlib.pyplot as plt\nfrom lifelines.statistics import multivariate_logrank_test\nfrom lifelines.statistics import pairwise_logrank_test\n```\n:::\n\n:::\n::::\n\nMuch the same as with a single continuous predictor, there are a few key values we can focus on when evaluating and reporting a more complex Cox regression model:\n\n- hazard ratios (based on our coefficients)\n- global significance tests (specifically, the likelihood ratio test)\n- concordance\n- individual significance tests\n\nWe may also want to:\n\n- make predictions using our model\n- visualise our model\n\nAll of these are discussed in this chapter. Throughout, we'll be using the model we fitted last chapter; rerun this code if the model is not already in your environment:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhospital_stays <- read_csv(\"data/hospital_stays.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 210 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (1): hospital_type\ndbl (6): time, discharged, age, sex, surgery, weekend_admission\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ncox_hosp_int <- coxph(Surv(time, discharged) ~ age * surgery + weekend_admission, \n                      data = hospital_stays)\n```\n:::\n\n:::\n\n## Hazard ratios\n\nWe can find the hazard ratios under the `exp(coef)` column of our model summary.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(cox_hosp_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, discharged) ~ age * surgery + weekend_admission, \n    data = hospital_stays)\n\n  n= 210, number of events= 189 \n\n                       coef exp(coef)  se(coef)      z Pr(>|z|)    \nage               -0.049991  0.951238  0.007702 -6.490 8.56e-11 ***\nsurgery           -0.052449  0.948903  0.654180 -0.080    0.936    \nweekend_admission -0.224911  0.798587  0.159536 -1.410    0.159    \nage:surgery       -0.006882  0.993141  0.010999 -0.626    0.531    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                  exp(coef) exp(-coef) lower .95 upper .95\nage                  0.9512      1.051    0.9370    0.9657\nsurgery              0.9489      1.054    0.2633    3.4203\nweekend_admission    0.7986      1.252    0.5842    1.0917\nage:surgery          0.9931      1.007    0.9720    1.0148\n\nConcordance= 0.695  (se = 0.022 )\nLikelihood ratio test= 85.41  on 4 df,   p=<2e-16\nWald test            = 83.32  on 4 df,   p=<2e-16\nScore (logrank) test = 89.56  on 4 df,   p=<2e-16\n```\n\n\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n:::\n\n\nWe already have some practice interpreting the hazard ratio for a continuous predictor such as `age`, from a [previous chapter](#sec_hazard-ratio).\n\n### Hazard ratios for categorical predictors\n\nFor our binary predictors `surgery` and `weekend_admission`, the 0 group will be chosen as our reference.\n\nThis means that our hazard ratios compare the hazard for the group coded 1, relative to the group 0 baseline.\n\nFor `surgery` we see a hazard ratio of 0.9489. If we use the [formula I previously](#sec_calculating-hazard-ratios) showed, that tells us that patients who receive surgery have a 5.11% lower hazard of experiencing the event. Since the event is being discharged, this means that they typically stay longer.\n\nFor `weekend_admission`, we see a hazard ratio of 0.7986, corresponding to a 20.14% reduction in hazard for those admitted on a weekend. In other words, being admitted to hospital on a weekend appears to make for a longer time-to-discharge.\n\n### Hazard ratios for interaction effects\n\nThe interpretation of hazard ratios for interactions is a little more complex, so bear with me here!\n\nFirstly, we can calculate from the `age` hazard ratio that there is a 4.88% decrease in the hazard for each unit increase in the predictor. In other words, for each year older a patient is, there is a 4.88% decrease in their chance of being discharged at any given point in time.\n\nSo how do we now interpret the extra interaction hazard ratio?\n\nOur model has estimated a hazard ratio of 0.9931 for the interaction. This corresponds to a 0.69% decrease in hazard.\n\nThis ratio/percentage describes how the effect of `age` on the hazard *changes* when we move between the non-surgical (baseline) and surgical groups.\n\nIn other words, for each one-year increase in age, the hazard ratio for age is 0.9931 times as large among patients who had surgery, compared with those who did not.\n\nSo, the effect of being older is *stronger* in the surgical group than the non-surgical group.\n\n::: callout-warning\nNote: this is **not** the same as saying that surgery reduces the hazard by 0.69 - this would be the main effect of `surgery`, which we have already calculated.\n\nThis is a common mistake with interaction terms!\n:::\n\n## Global significance test\n\nWe're focusing on the likelihood ratio test in this course, so let's extract the relevant information from the model summary.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(cox_hosp_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, discharged) ~ age * surgery + weekend_admission, \n    data = hospital_stays)\n\n  n= 210, number of events= 189 \n\n                       coef exp(coef)  se(coef)      z Pr(>|z|)    \nage               -0.049991  0.951238  0.007702 -6.490 8.56e-11 ***\nsurgery           -0.052449  0.948903  0.654180 -0.080    0.936    \nweekend_admission -0.224911  0.798587  0.159536 -1.410    0.159    \nage:surgery       -0.006882  0.993141  0.010999 -0.626    0.531    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n                  exp(coef) exp(-coef) lower .95 upper .95\nage                  0.9512      1.051    0.9370    0.9657\nsurgery              0.9489      1.054    0.2633    3.4203\nweekend_admission    0.7986      1.252    0.5842    1.0917\nage:surgery          0.9931      1.007    0.9720    1.0148\n\nConcordance= 0.695  (se = 0.022 )\nLikelihood ratio test= 85.41  on 4 df,   p=<2e-16\nWald test            = 83.32  on 4 df,   p=<2e-16\nScore (logrank) test = 89.56  on 4 df,   p=<2e-16\n```\n\n\n:::\n:::\n\n:::\n\n\n::: {.cell}\n\n:::\n\n\nWe get a $\\chi^2$ statistic of 85.4, with an associated p-value of 1.24\\times 10^{-17}.\n\nThis implies that our model is very significant over the null, i.e., our data are very unlikely to have occurred by random chance.\n\n## Concordance\n\nFrom our summary, we can also see a concordance of 0.695, which corresponds to an accuracy of 69.5%.\n\nIn other words, for all possible pairwise patient-patient comparisons across the dataset, our model correctly predicted which one of them \"should\" have been discharged first 69.5% of the time.\n\nThis is a relatively high number, without being unreasonably or suspiciously large, which is promising.\n\n## Individual significance tests\n\nFinally, we can examine the significance of the individual predictors in the model.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_hosp_int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\ncoxph(formula = Surv(time, discharged) ~ age * surgery + weekend_admission, \n    data = hospital_stays)\n\n                       coef exp(coef)  se(coef)      z        p\nage               -0.049991  0.951238  0.007702 -6.490 8.56e-11\nsurgery           -0.052449  0.948903  0.654180 -0.080    0.936\nweekend_admission -0.224911  0.798587  0.159536 -1.410    0.159\nage:surgery       -0.006882  0.993141  0.010999 -0.626    0.531\n\nLikelihood ratio test=85.41  on 4 df, p=< 2.2e-16\nn= 210, number of events= 189 \n```\n\n\n:::\n:::\n\n:::\n\nIn this model, only the `age` predictor has a significant coefficient.\n\nHowever - this does **not** imply that our other predictors have no value or explanatory power, and it doesn't automatically mean we should remove them from our model.\n\nIn the next chapter, we'll talk a little more about model comparison.\n\n## Making predictions\n\nYou can predict different things:\n\n- Risk score, representing relative hazard compared to the reference group\n- Survival probability for specific new data values\n- Survival curves for specific new data points\n\nLet's imagine we have three new patients that we want to make predictions for, using our existing model. We know their values for each of the three predictor variables that are included in their model, and we'd like to know how this affects their chances of being discharged.\n\n| Age | Surgery | Weekend admission |\n|-----|---------|-------------------|\n| 50  | 1       | 1                 |\n| 70  | 1       | 0                 |\n| 90  | 0       | 1                 |\n\nFirst, we're going to generate an object in our environment that contains these data, like so:\n\n::: {.panel-tabset group=\"language\"}\n## R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_subjects <- data.frame(age = c(50, 70, 90),\n                           surgery = c(1, 1, 0),\n                           weekend_admission = c(1, 0, 1))\n```\n:::\n\n:::\n\n### Relative risk scores\n\nOne thing we can obtain using these three new imaginary patients is something called a relative risk score for each of them.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\nTo do this, we use the `predict` function with the optional `type` argument set to `\"risk\"`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrisk_preds <- predict(cox_hosp_int, newdata = new_subjects, type = \"risk\")\nrisk_preds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2         3 \n0.9961297 0.3999402 0.2004948 \n```\n\n\n:::\n:::\n\n:::\n\nWhat do these numbers actually mean?\n\nThese behave a little bit like hazard ratios, comparing each imaginary patient to the baseline hazard estimated by our model.\n\n::: callout-tip\nFor a reminder of how baseline hazard works, you may wish to return to the slides from the second lecture of the course.\n:::\n\nSo, if we got a relative risk score of exactly 1, this would imply that the combination of predictor values corresponds to the model's baseline hazard.\n\nIf we get relative risk scores \\> 1, then the hazard is increased; scores \\< 1 imply that the hazard is decreased. (Note: in this case, increasing hazard is a good thing, because it means the patient is probably getting discharged quicker!)\n\nIn this case, all three of our patients are worse off than the baseline hazard to different degrees, but things look much less optimistic for our 90-year-old than our 50-year-old.\n\n### Survival probabilities\n\nAnother useful question we can ask is: \"for an individual with certain values of the predictor variables, what's the probability that they haven't experienced the event **by a particular time**?\"\n\nIn other words: we can predict the survival probability of an imaginary individual after a specific length of study duration.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\nFor this, we need a function called `predictSurvProb` from our new `pec` package.\n\nMake sure you've installed and loaded the package (see the top of this chapter for the code to do this if you need it).\n\nThe first step we need to follow is actually quickly refitting our model with an extra argument: `x = TRUE`. All this does is include the original dataset inside the model object that is created.\n\nThen,\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncox_hosp_int2 <- coxph(Surv(time, discharged) ~ age * surgery + weekend_admission,\n                       data = hospital_stays,\n                       x = TRUE)  \n```\n:::\n\n\nThen, we input our model, our set of imaginary patients, and a vector (of any length we want) of times that we'd like to make predictions for.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictSurvProb(object = cox_hosp_int2,                  \n                newdata = new_subjects,                  \n                times = c(20, 40, 60, 100))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'riskRegression':\n  method        from \n  nobs.multinom broom\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]       [,2]        [,3] [,4]\n[1,] 0.1224568 0.02206262 0.002844557   NA\n[2,] 0.4303587 0.21626590 0.095017119   NA\n[3,] 0.6552921 0.46411074 0.307298150   NA\n```\n\n\n:::\n:::\n\n:::\n\nEach row of the resulting object corresponds to one of our imaginary patients, and each column to one of our time points.\n\nFor example, row 1 corresponds to our 50-year-old. At 20 days in, the probability of that patient remaining in hospital (\"surviving\", i.e., not having been discharged) is around 12%. By 40 days, it's dropped to 0.2%.\n\nMeanwhile, in row 3, we have our 90-year-old. Even by 60 days, they still have a 31% chance of remaining in hospital without discharge.\n\n::: {.callout-warning icon=\"false\"}\nNote that in our 4th column, we get no predicted survival probabilities. That's because the value we entered, 100 days, goes beyond the length of the study.\n:::\n\n### Survival curves\n\nNow, let's go a step further: we can actually visualise an *entire* set of predictions for our three imaginary new patients, across the entire time period of our study.\n\n::: {.panel-tabset group=\"language\"}\n## R\n\nFirst, we need to generate the set of survival predictions; then, we can feed that into our `ggsurvplot` function to produce the familiar Kaplan-Meier survival curves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurv_preds <- survfit(cox_hosp_int, newdata = new_subjects)\nsurv_preds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall: survfit(formula = cox_hosp_int, newdata = new_subjects)\n\n    n events median 0.95LCL 0.95UCL\n1 210    189    7.5     6.0      12\n2 210    189   15.5    13.0      27\n3 210    189   38.5    20.5      NA\n```\n\n\n:::\n\n```{.r .cell-code}\nggsurvplot(surv_preds, \n           data = new_subjects,\n           surv.median.line = \"hv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 0, y = max(y2), xend = max(x1), yend = max(y2)), : All aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\nAll aesthetics have length 1, but the data has 3 rows.\nℹ Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](10-interpreting-multivariate-cox_files/figure-html/predicting survival curves-1.png){width=672}\n:::\n:::\n\n:::\n\nWhat are we actually visualising here?\n\nWell, these are *estimates* of the underlying \"true\" survival curve, for each set of predictor values that we fed into the function.\n\nFor example, if we had a dataset consisting entirely of 50-year-olds who received surgery and were admitted on a weekend, we might expect the survival curve to look something like the red curve above (assuming that the model we've fitted is accurate to reality).\n\n::: callout-note\n#### Where are the censoring events coming from?\n\nIn the curves above, there are several + signs indicating censoring events.\n\nBut of course, we're dealing with hypothetical survival curves here, based on new values of the predictors - so how can there be censoring?\n\nWell, it's because we're still basing our estimated curves on a model that was generated from a real dataset, and that dataset *did* contain censoring.\n\nAnother way of thinking about what we've done here is that for each of the three curves produced above, we've taken the original 210 patients and \"adjusted\" all of their values to match one row of our `new_subjects` dataframe.\n\nBut of those 210 patients, 21 were censored, and so that censoring carries over into each of the new curves we produce.\n:::\n\n## Visualising models\n\n## Summary\n\nWhile adding additional terms to the model doesn't make it much harder to fit the model itself, it does mean a more lengthy assumption-checking and interpretation procedure, and also makes it a little harder to visualise.\n\nHowever, it comes with the added benefit of being able to make more accurate predictions, and being able to examine potential interaction effects in the time-to-event dataset.\n\n::: callout-tip\n#### Key Points\n\n- Fitting Cox regression models with 2+ predictors (including interactions) follows the same simple syntax as fitting linear models with multiple predictors\n- Assumptions of proportional hazards and linearity are checked for each predictor individually/one by one, even when there are multiple predictors\n- We can use concordance and the global likelihood ratio test to evaluate and interpret our model as a whole, and use the model for making predictions about new data points\n- We can use individual p-values and hazard ratios to interpret individual predictors, if we are curious about the mechanisms driving \"survival\"\n- Visualisation of the model is more challenging when there are multiple predictors, and can involve\n:::\n",
    "supporting": [
      "10-interpreting-multivariate-cox_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}